#!/bin/bash

if [ -f /home/centos/.VALET_status ]; then
        status_key_word=$(cat /home/centos/.VALET_status)
        echo "$status_key_word"
	rm -f /home/centos/.VALET_status
else
	echo "none"
fi
